site_name: Physiopy
site_description: Physiopy
site_author: The Physiopy developers
site_url: https://physiopy.github.io

# Copyright
copyright: Copyright &copy; 2020-2024, The Physiopy Community

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  features:
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
    - Home: index.md
    - Libraries:
      - phys2bids: libraries/phys2bids.md
      - phys2denoise: libraries/phys2denoise.md
      - peakdet: libraries/peakdet.md
    - Community Practices:
      - Community Practices: https://physiopy-community-guidelines.readthedocs.io/en/latest/index.html
    - Contributor Guide: 
      - Goals: guide/goals.md
      - Getting started: guide/getting-started.md
      - Contributing to Codebase: guide/contributing-codebase.md
      - Contributing to Documentation: guide/contributing-documentation.md
    - Community:
      - Welcome: community/index.md
      - Getting Started: community/gettingstarted.md
      - Open Datasets: community/open_datasets.md
      - Other Tools: community/other_tools.md
      - Code of Conduct: community/CODE_OF_CONDUCT.md
      - Team: community/team.md
    - Tutorials:
      - OHBM 2023: ohbm23_tutorials.md
    - Events:
      - Events: events/events.md
      


